config/routes.rb
Rails.application.routes.draw do
  get 'my_plants/create'

  root 'home#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :plants
  resources :users do
    resources :my_plants
  end

  get '/dashboard', to: 'home#dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/my_plant.rb
class MyPlant < ApplicationRecord
  belongs_to :plants
  belongs_to :users
end

app/models/plant.rb
class Plant < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :my_plants

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @plants = Plant.all
  end

  def dashboard
    @my_plants = current_user.my_plants
  end
end

app/controllers/my_plants_controller.rb
class MyPlantsController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
    @my_plant = current_user.my_plants.new(plant_id: params[:plant_id])

    respond_to do |format|
      if @my_plant.save
        format.html { redirect_to root_path, notice: 'Plant was successfully added.' }
        format.json { render :show, status: :created, location: @my_plant }
      else
        format.html { redirect_to root_path, alert: @my_plant.errors }
        format.json { render json: @my_plant.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_plant, only: [:show, :edit, :update, :destroy]

  # GET /plants
  # GET /plants.json
  def index
    @plants = Plant.all
  end

  # GET /plants/1
  # GET /plants/1.json
  def show
  end

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants
  # POST /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: 'Plant was successfully created.' }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1
  # PATCH/PUT /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to @plant, notice: 'Plant was successfully updated.' }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.json
  def destroy
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants_url, notice: 'Plant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plant_params
      params.require(:plant).permit(:name, :sun, :germination, :season, :depth, :spacing, :days_to_harvest, :friends, :foes, :more_information)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/my_plants_helper.rb
module MyPlantsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/home/dashboard.html.erb
<h1>🐝 My Garden 🐞</h1>
<p>Track your garden.</p>

<h2>My Plants</h2>
<% @my_plants.each do |my_plant| %>
  <ul>
    <li style="list-style:none"><%= link_to my_plant.plant.name, my_plant.plant %></li>
  </ul>
<% end %>

app/views/home/index.html.erb
<div class="section">
  <div class="row">
    <div class="col-md-12">
      <div class="main-title page-header">
        <h1 class="text-center">🐝 Homesteady 🐞<br><small>Track your garden</small></h1>
        <div>
          <p class="text-center">
            <%= link_to 'Add Plant', new_plant_path, class: 'btn btn-primary' %>
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
        <% @plants.each do |plant| %>
          <ul>
            <div class="col-md-1">
              <li style="list-style:none"><%= link_to plant.name, plant %></li>
            </div>
          </ul>
        <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardenApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">🐝 Homesteady 🐞</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%- if current_user %>
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
              <%- else %>
                <%= link_to "Sign in", new_user_session_path %><br/>
              <%- end %>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/my_plants/create.html.erb
<h1>MyPlants#create</h1>
<p>Find me in app/views/my_plants/create.html.erb</p>

app/views/plants/_form.html.erb
<%= form_with(model: plant, local: true) do |form| %>
  <% if plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
      <% plant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :plant_name %>
  </div>

  <div class="field">
    <%= form.label :sun %>
    <%= form.text_field :sun, id: :plant_sun %>
  </div>

  <div class="field">
    <%= form.label :germination %>
    <%= form.text_field :germination, id: :plant_germination %>
  </div>

  <div class="field">
    <%= form.label :season %>
    <%= form.text_field :season, id: :plant_season %>
  </div>

  <div class="field">
    <%= form.label :depth %>
    <%= form.text_field :depth, id: :plant_depth %>
  </div>

  <div class="field">
    <%= form.label :spacing %>
    <%= form.text_field :spacing, id: :plant_spacing %>
  </div>

  <div class="field">
    <%= form.label :plant_height %>
    <%= form.number_field :plant_height, id: :plant_plant_height %>
  </div>

  <div class="field">
    <%= form.label :days_to_harvest %>
    <%= form.number_field :days_to_harvest, id: :plant_days_to_harvest %>
  </div>

  <div class="field">
    <%= form.label :friends %>
    <%= form.text_field :friends, id: :plant_friends %>
  </div>

  <div class="field">
    <%= form.label :foes %>
    <%= form.text_field :foes, id: :plant_foes %>
  </div>

  <div class="field">
    <%= form.label :more_information %>
    <%= form.text_area :more_information, id: :plant_more_information %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plants/edit.html.erb
<h1>Editing Plant</h1>

<%= render 'form', plant: @plant %>

<%= link_to 'Show', @plant %> |
<%= link_to 'Back', plants_path %>

app/views/plants/index.html.erb
<h1>Plants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Sun</th>
      <th>Germination</th>
      <th>Season</th>
      <th>Depth</th>
      <th>Spacing</th>
      <th>Height<th>
      <th>Days to harvest</th>
      <th>Friends</th>
      <th>Foes</th>
      <th>More information</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plants.each do |plant| %>
      <tr>
        <td><%= plant.name %></td>
        <td><%= plant.sun %></td>
        <td><%= plant.germination %></td>
        <td><%= plant.season %></td>
        <td><%= plant.depth %></td>
        <td><%= plant.spacing %></td>
        <td><%= plant.plant_height %></td>
        <td><%= plant.days_to_harvest %></td>
        <td><%= plant.friends %></td>
        <td><%= plant.foes %></td>
        <td><%= plant.more_information %></td>
        <td><%= link_to 'Show', plant %></td>
        <td><%= link_to 'Edit', edit_plant_path(plant) %></td>
        <td><%= link_to 'Destroy', plant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plant', new_plant_path %>

app/views/plants/new.html.erb
<h1>New Plant</h1>

<%= render 'form', plant: @plant %>

<%= link_to 'Back', plants_path %>

app/views/plants/show.html.erb
<p><- <%= link_to 'Back to index', plants_path %></p>

<p>
  <strong>Name:</strong>
  <%= @plant.name %>
</p>

<p>
  <strong>Sun:</strong>
  <%= @plant.sun %>
</p>

<p>
  <strong>Germination:</strong>
  <%= @plant.germination %>
</p>

<p>
  <strong>Season:</strong>
  <%= @plant.season %>
</p>

<p>
  <strong>Depth:</strong>
  <%= @plant.depth %>
</p>

<p>
  <strong>Spacing:</strong>
  <%= @plant.spacing %>
</p>

<p>
  <strong>Height:</strong>
  <%= @plant.plant_height %>
</p>

<p>
  <strong>Days to harvest:</strong>
  <%= @plant.days_to_harvest %>
</p>

<p>
  <strong>Friends:</strong>
  <%= @plant.friends %>
</p>

<p>
  <strong>Foes:</strong>
  <%= @plant.foes %>
</p>

<p>
  <strong>More information:</strong>
  <%= @plant.more_information %>
</p>

<%= link_to 'Edit', edit_plant_path(@plant) %>